name: webirr
version: 1.0.3
description: >-
  Official Dart Client Library for WeBirr Payment Gateway APIs.     
  This Library provides convenient access to WeBirr Payment Gateway APIs from Dart/Flutter Apps. 
homepage: https://github.com/webirr/webirr-api-dart-client
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  http: ^0.13.3
dev_dependencies: 
  test: ^1.17.10
