name: webirr
version: 1.0.0
description: >-
  Official Dart Client Library for WeBirr APIs 
homepage: https://github.com/webirr/webirr-api-dart-client
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  http: ^0.13.3